services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-setup:
    build:
      context: .
    environment:
      RAILS_ENV: development
    command: bundle exec bin/rails db:prepare
    volumes:
      - .:/app
    depends_on:
      - db

  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
      - db-setup
    environment:
      RAILS_ENV: development
      SECRET_KEY: ${SECRET_KEY}
      PETALA_AUTOMATION_SYSTEM_WEB_URL: ${PETALA_AUTOMATION_SYSTEM_WEB_URL}

volumes:
  postgres_data:
