services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  db-setup:
    build: .
    environment:
      RAILS_ENV: development
    command: bundle exec bin/rails db:prepare
    volumes:
      - .:/app
    depends_on:
      - db
    restart: "no"

  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
      - db-setup
    environment:
      RAILS_ENV: development
      SECRET_KEY: ${SECRET_KEY}
      PETALA_AUTOMATION_SYSTEM_WEB_URL: ${PETALA_AUTOMATION_SYSTEM_WEB_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      
volumes:
  postgres_data:
