# API specifications settings
api:
  docs:
    auth:
      password: ''
      username: ''
    root: 'swagger'
    versions:
      - default_host: ''
        description: 'Petala Automation System Service Docs'
        endpoint: 'v1/swagger.yaml'
        id: 'v1/swagger.yaml'
        openapi: '3.0.3'
        title: 'Petala Automation System Service'
        version: 'v1'
  schemas:
    error_response:
      type: 'object'
      properties:
        error:
          $ref: '#/components/schemas/exception'
      required:
        - 'error'
    exception:
      type: 'object'
      properties:
        id:
          type: 'string'
        message:
          type: 'string'
    create_user:
      type: 'object'
      properties:
        user:
          type: 'object'
          properties:
            email:
              type: 'string'
            password:
              type: 'string'
            role:
              type: 'integer'
    user:
      type: 'object'
      properties:
        email:
          type: 'string'
        name:
          type: 'string'
        cpf:
          type: 'string'
        phone:
          type: 'string'
        roles:
          type: 'string'
    user_response:
      type: 'object'
      properties:
        id:
          type: 'integer'
        email:
          type: 'string'
    change_password:
      type: 'object'
      properties:
        new_password:
          type: 'string'
    session_response:
      type: 'object'
      properties:
        session_token:
          type: 'string'
    company:
      type: 'object'
      properties:
        name:
          type: 'string'
        cnpj:
          type: 'string'
        cep:
          type: 'string'
        street:
          type: 'string'
        number:
          type: 'integer'
        city:
          type: 'string'
        state:
          type: 'string'
        user_id:
          type: 'integer'
    company_update:
      type: 'object'
      properties:
        name:
          type: 'string'
        cnpj:
          type: 'string'
        cep:
          type: 'string'
        street:
          type: 'string'
        number:
          type: 'integer'
        city:
          type: 'string'
        state:
          type: 'string'
    order:
      type: 'object'
      properties:
        admin_feedback:
          type: 'string'
          nullable: true
        status:
          type: 'string'
          default: 'pending'
        description:
          type: 'string'
        company_id:
          type: 'integer'
    order_update:
      type: 'object'
      properties:
        admin_feedback:
          type: 'string'
          nullable: true
        status:
          type: 'string'
          default: 'pending'
    order_item:
      type: 'object'
      properties:
        code:
          type: 'string'
        product:
          type: 'string'
        price:
          type: 'string'
        quantity:
          type: 'integer'
        ean_code:
          type: 'string'
        total:
          type: 'string'
        order_id:
          type: 'integer'
    order_item_update:
      type: 'object'
      properties:
        code:
          type: 'string'
        product:
          type: 'string'
        price:
          type: 'string'
        quantity:
          type: 'integer'
        ean_code:
          type: 'string'

cors:
  allowed_origins: <%= ENV.fetch('PETALA_AUTOMATION_SYSTEM_WEB_URL') { 'http://localhost:3000' } %>

database:
  name: <%= ENV.fetch('DB_NAME') { nil } %>
  user: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  pass: <%= ENV.fetch('DB_PASS') { 'postgres' } %>
  host: <%= ENV.fetch('DB_HOST') { 'db' } %>

secret_key: <%= ENV.fetch('SECRET_KEY') { '' } %>

petala_automation_system_web_url: <%= ENV.fetch('PETALA_AUTOMATION_SYSTEM_WEB_URL') { 'http://localhost:3000' } %>

i18n:
  available_locales:
    - en
    - pt-BR
  default_locale: 'pt-BR'
